### ISSUE TITLE
Misbehaving h3

### ISSUE THREAD

**Issue by kaybow** [kaybow/dsn1674-project-3#2]
Hi Thomas,

I'm having an issue with my h3 "Contact Us"—when the browser is stretched and reduced in size, my h3 fluctuates from spanning across the entire width, to only half the width, and back, seemingly at random. Do you know what may cause this and how to fix it? I recently put overflow: hidden on the h3 as it was underneath my fig captions above it.

@thomasjbradley

**Comment by thomasjbradley** [comment]
It's a clearing issue; add `clear: both` to it.
